case class CreateUser(pFirstName : String, pLastName : String, pGender : Gender.EnumVal)
case class CreateUsers()
case class AddFriends(numOfUsers : Int)
case class StartActivities()
case class CreatePage(pPageName : String)